#!/usr/bin/env python3
"""Run a scene_event_cg seed batch from compact emotion/framing intent.

Default is safe dry-run/prepare-only style when --dry-run is passed. Without
--dry-run, this calls run_scene_event_cg_smoke.py once per seed and records the
verified candidate path when generation succeeds.
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from datetime import datetime
from pathlib import Path

from scene_event_cg_policy import build_reference_conditioning_request, build_scene_event_cg_prompt_slots
from create_scene_event_cg_prompt_slots import DEFAULT_CHARACTER_FEATURES, DEFAULT_OUTFIT_DETAIL, DEFAULT_SCENE_CONTEXT, parse_tags

ROOT = Path(__file__).resolve().parents[1]
RUNNER = ROOT / 'tools/run_scene_event_cg_smoke.py'


def parse_seeds(value: str) -> list[int]:
    seeds = []
    for part in str(value or '').split(','):
        part = part.strip()
        if not part:
            continue
        seeds.append(int(part))
    if not seeds:
        raise RuntimeError('SCENE_EVENT_BATCH_SEEDS_REQUIRED')
    return seeds


def slugify_asset_id(value: str) -> str:
    slug = re.sub(r'[^A-Za-z0-9_]+', '_', str(value or '').strip()).strip('_')
    slug = re.sub(r'_+', '_', slug)
    if not slug:
        raise RuntimeError('SCENE_EVENT_BATCH_ASSET_ID_PREFIX_REQUIRED')
    return slug


def require_under(path: Path, root: Path, label: str) -> Path:
    resolved = path.resolve()
    root = root.resolve()
    try:
        resolved.relative_to(root)
    except ValueError as exc:
        raise RuntimeError(f'{label.upper()}_MUST_BE_UNDER_PROJECT_ROOT: {resolved} not under {root}') from exc
    return resolved


def parse_csv(value: str) -> list[str]:
    return [part.strip() for part in str(value or '').split(',') if part.strip()]


def parse_reference_assets(value: str, project_root: Path) -> list[str]:
    assets = []
    for raw in parse_csv(value):
        path = Path(raw)
        resolved = require_under(path if path.is_absolute() else project_root / path, project_root, 'reference_asset')
        assets.append(str(resolved))
    return assets


def latest_run_metadata(project_root: Path, asset_id: str) -> Path | None:
    run_root = project_root / 'docs/automation/generation_runs'
    candidates = sorted(run_root.glob(f'scene_event_cg_{asset_id}_*/metadata.json'))
    return candidates[-1] if candidates else None


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--project-root', required=True)
    parser.add_argument('--asset-id-prefix', required=True)
    parser.add_argument('--emotion', default='neutral')
    parser.add_argument('--framing', default='default')
    parser.add_argument('--seeds', required=True, help='Comma-separated seed list')
    parser.add_argument('--char-base-metadata', required=True)
    parser.add_argument('--scene-id', default='scene_event_cg_batch')
    parser.add_argument('--description', default='scene_event_cg batch generated by automation v2')
    parser.add_argument('--character-features')
    parser.add_argument('--outfit-detail')
    parser.add_argument('--scene-context')
    parser.add_argument('--subject-count', type=int, default=1)
    parser.add_argument('--interaction', default='none')
    parser.add_argument('--subjects', default='', help='Comma-separated character ids, e.g. serena,lucian')
    parser.add_argument('--reference-conditioning-mode', default='none')
    parser.add_argument('--reference-assets', default='', help='Comma-separated reference asset paths, confined under project root')
    parser.add_argument('--reference-reason', default='')
    parser.add_argument('--dry-run', action='store_true')
    parser.add_argument('--prepare-only', action='store_true', help='Call runner with --prepare-only instead of live generation')
    parser.add_argument('--output', help='Optional batch summary path')
    parser.add_argument('--allow-generic-fixture-defaults', action='store_true', help='Allow Unit 10 generic schoolgirl/auditorium fixture defaults. Unsafe for production unless explicitly requested.')
    args = parser.parse_args()

    project_root = Path(args.project_root).resolve()
    seeds = parse_seeds(args.seeds)
    asset_id_prefix = slugify_asset_id(args.asset_id_prefix)
    batch_root = require_under(project_root / 'docs/automation/batches', project_root, 'batch_root')
    batch_root.mkdir(parents=True, exist_ok=True)
    output = require_under(Path(args.output).resolve() if args.output else batch_root / f'{asset_id_prefix}_scene_event_cg_batch.json', project_root, 'output')
    prompt_slots_root = require_under(project_root / 'docs/production/prompt_slots', project_root, 'prompt_slots_root')
    fixture_defaults = args.allow_generic_fixture_defaults
    subjects = parse_csv(args.subjects)
    reference_conditioning = build_reference_conditioning_request(
        mode=args.reference_conditioning_mode,
        reference_assets=parse_reference_assets(args.reference_assets, project_root),
        reason=args.reference_reason or None,
    )

    items = []
    for index, seed in enumerate(seeds, start=1):
        asset_id = f'{asset_id_prefix}_s{seed}'
        prompt_slots_path = require_under(prompt_slots_root / f'{asset_id}.json', prompt_slots_root, 'prompt_slots_path')
        prompt_slots = build_scene_event_cg_prompt_slots(
            asset_id=asset_id,
            emotion=args.emotion,
            framing=args.framing,
            base_character_features=parse_tags(args.character_features, DEFAULT_CHARACTER_FEATURES if fixture_defaults else None, label='character_features'),
            base_outfit_detail=parse_tags(args.outfit_detail, DEFAULT_OUTFIT_DETAIL if fixture_defaults else None, label='outfit_detail'),
            base_scene_context=parse_tags(args.scene_context, DEFAULT_SCENE_CONTEXT if fixture_defaults else None, label='scene_context'),
            subject_count=args.subject_count,
            subjects=subjects,
            interaction=args.interaction,
            reference_conditioning=reference_conditioning,
            visual_brief=f'{args.description}; batch item {index}; seed {seed}',
        )
        prompt_slots_path.parent.mkdir(parents=True, exist_ok=True)
        prompt_slots_path.write_text(json.dumps(prompt_slots, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
        command = [
            sys.executable,
            str(RUNNER),
            '--project-root',
            str(project_root),
            '--asset-id',
            asset_id,
            '--scene-id',
            args.scene_id,
            '--description',
            f'{args.description}; seed {seed}',
            '--char-base-metadata',
            str(Path(args.char_base_metadata).resolve()),
            '--prompt-slots',
            str(prompt_slots_path),
            '--seed',
            str(seed),
        ]
        if args.dry_run or args.prepare_only:
            command.append('--prepare-only')
        item = {
            'index': index,
            'asset_id': asset_id,
            'seed': seed,
            'emotion': args.emotion,
            'framing': args.framing,
            'subject_count': prompt_slots.get('subject_count'),
            'subjects': prompt_slots.get('subjects') or [],
            'interaction': prompt_slots.get('interaction'),
            'review_gate': prompt_slots.get('review_gate'),
            'executable': prompt_slots.get('executable'),
            'reference_conditioning': prompt_slots.get('reference_conditioning'),
            'scene_event_route_mode': prompt_slots['scene_event_route_mode'],
            'prompt_slots': str(prompt_slots_path),
            'command': command,
            'status': 'dry_run' if args.dry_run else 'pending',
        }
        if not args.dry_run:
            proc = subprocess.run(command, cwd=ROOT, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
            item['runner_returncode'] = proc.returncode
            item['runner_output_tail'] = proc.stdout[-4000:]
            if proc.returncode != 0:
                item['status'] = 'failed'
                items.append(item)
                summary = {
                    'workflow_id': 'scene_event_cg',
                    'created_at': datetime.now().isoformat(timespec='seconds'),
                    'dry_run': args.dry_run,
                    'items': items,
                }
                output.write_text(json.dumps(summary, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
                raise RuntimeError(f'Batch item failed: {asset_id}; see {output}')
            meta_path = latest_run_metadata(project_root, asset_id)
            if meta_path:
                meta = json.loads(meta_path.read_text(encoding='utf-8'))
                item['run_id'] = meta.get('run_id')
                copies = meta.get('candidate_copies') or []
                if copies:
                    item['candidate'] = copies[0]
                item['status'] = 'generated'
            else:
                item['status'] = 'generated_metadata_missing'
        items.append(item)

    summary = {
        'workflow_id': 'scene_event_cg',
        'created_at': datetime.now().isoformat(timespec='seconds'),
        'project_root': str(project_root),
        'asset_id_prefix': asset_id_prefix,
        'emotion': args.emotion,
        'framing': args.framing,
        'dry_run': args.dry_run,
        'prepare_only': args.prepare_only,
        'items': items,
        'promotion_status': 'not_promoted_pending_owner_approval',
    }
    output.write_text(json.dumps(summary, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
    print(f'BATCH_SUMMARY {output}')
    print(f'ITEMS {len(items)}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
